export const CONFIG = {
  groom: 'XXX',
  bride: 'XXX',
  groomFather: 'XXX',
  groomMother: 'XXX',
  brideFather: 'XXX',
  brideMother: 'XXX',
  weddingTitle: 'The Wedding of XXX & XXX',
  weddingDateLabel: 'XXX',
  eventStart: '2026-12-12T10:00:00+08:00',
  eventEnd: '2026-12-12T14:00:00+08:00',
  venueName: 'XXX',
  venueAddress: 'XXX',
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=XXX',
  calendarDescription: 'Please join us to celebrate our wedding day.',
  bankName: 'XXX Bank',
  bankAccount: 'XXX',
  bankAccountName: 'XXX',
  giftAddress: 'XXX',
  appsScriptUrl: 'PASTE_WEB_APP_URL_HERE',
  wishesRefreshMs: 15000
};
